{% set version = "3.8.0" %}

package:
  name: easybuild
  version: {{ version }}

source:
  fn: easybuild-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild/easybuild-{{ version }}.tar.gz
  sha256: 50c1bf19341f262c118d977025d2da382390fb74c58db6f7266a8d9d966d62eb
  patches:
    - setup_py.patch

build:
  number: 1000
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - easybuild-easyconfigs 3.5.0
    - easybuild-easyblocks 3.5.0
    - easybuild-framework 3.5.0
  run:
    - python
    - easybuild-easyconfigs 3.5.0
    - easybuild-easyblocks 3.5.0
    - easybuild-framework 3.5.0

test:
  imports:
    - easybuild
  commands:
    - eb --help

about:
  home: http://hpcugent.github.com/easybuild
  license: GPLv2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'EasyBuild is a software build\nand installation framework that allows you to manage (scientific) software\non High Performance Computing (HPC) systems in an efficient way.'
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
