{% set version = "4.7.0" %}

package:
  name: easybuild
  version: {{ version }}

source:
  fn: easybuild-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild/easybuild-{{ version }}.tar.gz
  sha256: e68c280e3a508965aefbdf234872919f777f739cf4787cb11bb97a56e0cf74a6
  patches:
    - setup_py.patch

build:
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - easybuild-easyconfigs {{ version }}
    - easybuild-easyblocks {{ version }}
    - easybuild-framework {{ version }}
  run:
    - python
    - easybuild-easyconfigs {{ version }}
    - easybuild-easyblocks {{ version }}
    - easybuild-framework {{ version }}

test:
  imports:
    - easybuild
  commands:
    - eb --help

about:
  home: http://hpcugent.github.com/easybuild
  license: GPLv2
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: EasyBuild is a software build\nand installation framework that allows you to manage (scientific) software\non High Performance Computing (HPC) systems in an efficient way.
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
