travis:
  secure:
    BINSTAR_TOKEN: QEjnBB4Wz8p4RJdZxiR8G+9EaM1Or2EPYg7hSDLN45t7u1AoUFD6X9WIvozmOUZ2oI6Cd69u4dIii4VALgMbmPohUr/HXoBmwba7g0VGXA7j72U9b/Q0Gh3iLy/JkLqav9EuqEghFHCziKm7uMdVXc1vXqrkzpAFKseC3L8VBqaafRnl9UOyV0ljB+I+FdkZg3N1K2oJIgDKCz3aSWad5ZZPY0PQbT1636G3sJrclhAEPdWkWtiO1o1Sth3k4tIRnMcc6NZeE3ZG2TZWWql3I0g9xLoADFxV+1KnDhjMzUcMRf4xqPiGBnIfIiYGlSgvt8o9m2aTxFbb7owsOeBARFN+AyMVanvez2qYJPNkfKlhuAGWvGRB7qaHbr1rT40OhigCuofCH3yFcMnv7fB2zbFo5k6tJNWumEHGILt7zNSFOYuRab/PV47dVfVqgK+5KetA7I8Wim3lEaUdOWZFGmqZHTqKRc4vomY7H80Gu5ZRKPS9XubSAyE8JiYPIflcwTOcS1kNG7YkM9Yf7AThIMD3FlQDr8438yEIgJ9DgKgEVwcE8KChYsDoX2xg1dcQaOzAh/fjQQ/fACX2R1RhGM6LBh2ymm3Le2Jkn71WndreSEzG4vVr/ZuA4Sjr4vas4/UUSHFzxGiCTdQEnqqYrSoKWt/wlrnEIVf0cXh3kUk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
