appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: U3rbnX2bZKgeodaAKbEpYkifa0LPvm0RyZ98JdMFK5Du+THaYUJNJnKen6R5bkElIvbh3xV+WlwfwSFbqeRx9QDmOPZc7hxcnOQ0QDzhHKGNeWdcbNNkEd+vAT+cO857U6clMpIHvf9CnddP5lYY9MDYrerO75llzl79vsBoa5yNIGXIlvpWsL/QfjiKBuPACsSFYCC9sZQIbwjK+X0soY0qiJ6VEHzYD2EgOQlD/RSSCKePmxpPSvqTeDZBQgG9F/Z641hsRvBxGrQ9tAoUnVvMGnzO5Eb/lj1CFops6sWzxklX6Lp1yxT+g6nwdCE+mWJ54SCjCixFrPILxnQoVcJ+nmcVxHRYfO8YeNDBsuhlVb1WF/yNfnj9i+oorsthb5e1iVO5MYql5Kib9W66F7kCYCcgt/3icQQoHqxDtj0ejmG3WMX9soVN9L2DJHkmeYnOakGbLwCJV8XEkZzwVFsya+7LS9yKHKe4BNnKMoncKjJny1VfFDyIdyh644unFJVOxNOKBxNtCHTBVpeQzc2epx/LP3G49rj1H8EvrXfA4ihwCyeJj0GGlMmeI6G51TYrB+P/nSCRVZ/PVEMxb1o0n+heXb/a0j2myZn1a0a1dI7JZh94XPxYPm8LZrCA05dQuScS6N3cOGIIHwAHwzHOBgmdISHjhqSKqOl28C8=}
conda_forge_output_validation: true
